name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
  - uses: actions/setup-java@v3
    with:
      java-version: '11'
      distribution: 'adopt'
  
  - name: Install Firefox
    run: sudo apt-get install -y firefox
      - name: Start SUT
        # Запускаем SUT,
        # имя файла SUT будет отличаться в каждой задаче.
        # & означает, что в фоновом режиме не блокируем терминал для запуска тестов,
        # обязательно должен быть для запуска SUT в CI
        run: java -jar ./artifacts/app-order.jar &
      - name: Build with Gradle
        # Запускаем автотесты
        # Для проектов на базе Selenide необходимо добавить параметр для запуска браузера
        # в headless режиме -Dselenide.headless=true, параметр --info должен остаться
        run: ./gradlew test --info
    
  
