name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Install Firefox (ESR version)
        run: |
          sudo add-apt-repository ppa:mozillateam/ppa -y
          sudo apt-get update
          sudo apt-get install -y firefox-esr
          firefox-esr --version

      - name: Install GeckoDriver
        run: |
          sudo apt-get install -y wget
          GECKO_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep tag_name | cut -d '"' -f 4)
          wget https://github.com/mozilla/geckodriver/releases/download/${GECKO_VERSION}/geckodriver-${GECKO_VERSION}-linux64.tar.gz
          sudo tar -xzf geckodriver-*.tar.gz -C /usr/local/bin
          geckodriver --version

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Start and verify SUT
        run: |
          java -jar ./artifacts/app-order.jar &
          sleep 5
          curl -v http://localhost:9999 || echo "SUT may not be responding"
        
      - name: Run tests with Gradle
        run: ./gradlew test --info
        env:
          MOZ_HEADLESS: 1
          FIREFOX_BIN: /usr/bin/firefox-esr
          GECKODRIVER_PATH: /usr/local/bin/geckodriver

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            build/reports/tests/
            build/test-results/
